spring.application.name=device-service

server.port=5052
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

management.endpoints.web.exposure.include=health,info

device.credential.expiry-days=${DEVICE_CREDENTIAL_EXPIRY_DAYS:365}